### ISSUE TITLE
mxml 3.0 compatibility

### ISSUE THREAD

**Issue by dvzrv** [paulnasca/paulstretch_cpp#11]
[mxml 3.0](https://github.com/michaelrsweet/mxml/releases) introduced quite some changes and it would be great, if this could be incorporated into this software (which is currently in [Arch Linux' [community] repository](https://www.archlinux.org/packages/community/x86_64/paulstretch/)).

Here's how zynaddsubfx and yoshimi are/were dealing with the changes: https://github.com/zynaddsubfx/zynaddsubfx/pull/22
https://github.com/Yoshimi/yoshimi/commit/9d5c05b3bb7c87a87f4ddeded9ae30c06bb7eeec

If this is not feasible and the application is not functional after upgrade to 3.0, I will have to remove it from the repositories.

Thanks!

**Comment by afontenot** [comment]
@dvzrv I doubt this is still maintained, but feel free to include my pull request fixing this as a patch.

**Comment by afontenot** [comment]
Note that the program is currently segfaulting for me, but as far as I can tell that doesn't have anything to do with mxml.

**Comment by dmorawski** [comment]
Thanks so much for this fix!
