### ISSUE TITLE
PaulStretch 64bit macOS Catalina support?

### ISSUE THREAD

**Issue by esaruoho** [paulnasca/paulstretch_cpp#13]
Can PaulStretch work on macOS Catalina, and what would it require for there to be an executable that supports 64bit?

**Comment by jathayde** [comment]
`libmxml` and `audiofile` do not yet have Catalina bottles in Homebrew. I also think there are issues with MXML 3.x (the Mojave bottle is 3.1). 

Looking at the previous Mac Build (http://music.cornwarning.com/2011/12/07/new-paulstretch-os-x-build/ which has the CMAKE scripts, etc included) it calls out that one of the dependencies requires 32 bit. Perhaps this could be rebuilt, but it's beyond my skill to make work right now.

**Comment by calebjamessound** [comment]
hello! i'm a music producer and need this to work on Caalina! i have NO
IDEA what you fantastic coding nerds are talking about but please, if there
is anything i can do to help you make this work it would be dope af!

*-- *
*caleb j. hoskins*
calebjamesmusic <https://soundcloud.com/calebjamesmusic>
instagram <http://www.instagram.com/calebjamesmusic>
<http://www.linkedin.com/in/calebhoskins>
<http://www.instagram.com/calebjames.png>

**Comment by mdznr** [comment]
@calebhoskins I found someone that made a 64-bit version here: https://xenakios.wordpress.com/paulstretch/

**Comment by calebjamessound** [comment]
thank you!
*-- *
*caleb hoskins*
*314.540.8998*

**Comment by akx** [comment]
I [forked Paulstretch](https://github.com/akx/paulstretch), merged some of these languishing PRs fixed up a thing or two – if/when you're running Homebrew, you can now install paulstretch with `brew install akx/things/paulstretch` ([formula here so you can see I'm not doing shenanigans](https://github.com/akx/homebrew-things/blob/master/Formula/paulstretch.rb)) and then run it with `paulstretch` on the command line.

Works fine on Catalina 10.15.3.

![Screenshot 2020-02-13 at 14 21 34](https://user-images.githubusercontent.com/58669/74434992-2d336980-4e6c-11ea-893f-c2952773b09f.png)

**Comment by akx** [comment]
There's now also a directly downloadable .dmg with a Catalina compatible build. https://github.com/akx/paulstretch/releases/tag/v2.2-3

**Comment by calebjamessound** [comment]
thank you so very much!
*-- *
*caleb hoskins*
*314.540.8998*

**Comment by ImaxGuy** [comment]
So thankful for Catalina support! I'm also running this on  Big Sur, beta 6. It will process files, but the transport controls don't work for the purposes of auditioning. Interestingly enough, this reminds me if the EMU Emax II SE additive synth package that allowed you to establish settings and the only way to hear the results were to commit to processing. PaulStretch is still pretty darn fantastic, though!

**Comment by esaruoho** [comment]
@akx thanks, have you btw tried to get in touch with the @paulnasca guy to get your fixes added onto this repo, too?
